### ISSUE TITLE
Bold fonts are cut off from the top

### ISSUE THREAD

**Issue by txtsd** [lxqt/qterminal#282]
![screenshot of font](https://i.imgur.com/07VS9Ei.png)

**Comment by yan12125** [comment]
Which font are you using?

**Comment by txtsd** [comment]
PragmataPro Mono, but the problem exists with DejaVu Sans Mono, Hack, and Input.

Also, those fat lines are not supposed to look like that at all. They're supposed to be the width of the brackets.

**Comment by agaida** [comment]
it might be interesting to know the distribution and the version

**Comment by txtsd** [comment]
@agaida 
OS: Archlinux
qterminal version: 0.7.0
Qt: 5.7.0

**Comment by txtsd** [comment]
Do I need to provide anything else to help us find the cause of this issue?

**Comment by yan12125** [comment]
I use DejaVu Sans Mono and everything looks normal. PragmataPro requires fee so I didn't test it.

I'm also on Arch Linux with Qt 5.7.0. Unless somebody can reproduce your problem, I'm afraid you'll need to debug by yourself.

**Comment by yan12125** [comment]
Actually QTerminal just calls Qt's [drawText](http://doc.qt.io/qt-5/qpainter.html#drawText) function to put texts onto the screen. Maybe there's something wrong in Qt.

**Comment by txtsd** [comment]
Here's how DejaVu Sans Mono 9pt looks for me. Even the non-bold brackets, parens, braces, and caret, are cut off.
![DejaVu Sans Mono 9pt](https://i.imgur.com/PLlncYZ.png)

**Also**, I can't find a drawText anywhere in this repo :(

**Comment by yan12125** [comment]
drawText is here: https://github.com/lxde/qtermwidget/blob/58f96bacb3020ab41be4d7a91316e214ed0fcc33/lib/TerminalDisplay.cpp#L830

And you reminds me that there's a possibly related patch at https://github.com/lxde/qtermwidget/pull/49

**Comment by agaida** [comment]
should be fixed long ago

**Comment by vxid** [comment]
I still see this issue using PragmataPro, even though it is not as bad as the screenshots above

![Fotoram io](https://user-images.githubusercontent.com/16440823/64962086-1970e080-d897-11e9-9480-e9c15969fc3e.png)

It is particularly noticeable when using a non-dark background color (for instance in dialog).

I use the latest Arch Linux release of qterminal.

**Comment by agaida** [comment]
and we will do nothing against

**Comment by tsujan** [comment]
If there is a problem and the cause is either in Qt or in a single font, I'd get suspicious of the latter.
